runtime: go115 # Указание используемой версии Go
env: flex # Указание на использование гибкого окружения

service: wb-l0 # Имя сервиса

env_variables: # Определение переменных окружения
  DB_HOST: "127.0.0.1"
  DB_PORT: "5432"
  DB_USER: "user"
  DB_PASSWORD: "password"
  DB_NAME: "db"
  NATS_URL: "nats://127.0.0.1:4222"