version: '3.9'
services:
  app_1:
    image: golang:alpine
    container_name: app
   # volumes:
      #- C:\Users\Admin\wb-l0\cmd\:/app
    #working_dir: /app
    build:
     dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - nats

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432" # Открываем порт для подключения с машины хоста

  nats:
    image: nats-streaming:alpine # Используем NATS Streaming Server на Alpine
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222